apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ai-services.ollama.fullname" . }}
  namespace: {{ include "ai-services.namespace" . }}
  labels:
    {{- include "ai-services.labels" . | nindent 4 }}
    {{- include "ai-services.ollama.selectorLabels" . | nindent 4 }}
data:
  OLLAMA_HOST: {{ .Values.ollama.config.host | quote }}
  OLLAMA_NUM_PARALLEL: {{ .Values.ollama.config.numParallel | quote }}
