{{- if .Values.ollama.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ai-services.ollama.fullname" . }}
  namespace: {{ include "ai-services.namespace" . }}
  labels:
    {{- include "ai-services.labels" . | nindent 4 }}
    {{- include "ai-services.ollama.selectorLabels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.ollama.persistence.accessMode }}
  storageClassName: {{ .Values.ollama.persistence.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.ollama.persistence.size }}
{{- end }}
